### ISSUE TITLE
Bring ENS resolver fix over from daohaus-app

### ISSUE THREAD

**Issue by plor** [HausDAO/daohaus-yeeter-v2#104]
This was fixed in https://github.com/HausDAO/daohaus-app/issues/1731 but the ens util needs to be copied over to have it work in the yeeter.

**Comment by brossetti1** [comment]
for reference - https://github.com/HausDAO/daohaus-app/pull/1836

**Comment by earth2travis** [comment]
Added to Dework: https://app.dework.xyz/y33t-by-daohaus/yeeter-board?taskId=6404e545-bb81-43a4-8607-39a34b432d3c
